server:
  port: 8081
  servlet:
    context-path: /indentity1
Spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/indentity1"
    username: root
    password: 12345
  jpa:
    properties:
      ddl-auto: update
      default_schema: indentity1
    show-sql: true